In [1]:
import numpy as np 
import pandas as pd

# Reading and Writing Data in Text Format

### Text and binary data loading functions in pandas

| Function | Description |
| :--- | :--- |
| `read_csv` | Load delimited data from a file, URL, or file-like object; use comma as default delimiter |
| `read_fwf` | Read data in fixed-width column format (i.e., no delimiters) |
| `read_clipboard` | Variation of `read_csv` that reads data from the clipboard; useful for converting tables from web pages |
| `read_excel` | Read tabular data from an Excel XLS or XLSX file |
| `read_hdf` | Read HDF5 files written by pandas |
| `read_html` | Read all tables found in the given HTML document |
| `read_json` | Read data from a JSON (JavaScript Object Notation) string representation, file, URL, or file-like object |
| `read_feather` | Read the Feather binary file format |
| `read_orc` | Read the Apache ORC binary file format |
| `read_parquet` | Read the Apache Parquet binary file format |
| `read_pickle` | Read an object stored by pandas using the Python pickle format |
| `read_sas` | Read a SAS dataset stored in one of the SAS system's custom storage formats |
| `read_spss` | Read a data file created by SPSS |
| `read_sql` | Read the results of a SQL query (using SQLAlchemy) |
| `read_sql_table` | Read a whole SQL table (using SQLAlchemy); equivalent to using a query that selects everything in that table using `read_sql` |
| `read_stata` | Read a dataset from Stata file format |
| `read_xml` | Read a table of data from an XML file |

In [2]:
!type ..\examples\ex1.csv

a,b,c,d,message
1,2,3,4,hello
5,6,7,8,world
9,10,11,12,foo

In [3]:
df = pd.read_csv("../examples/ex1.csv")

In [4]:
df

   a   b   c   d message
0  1   2   3   4   hello
1  5   6   7   8   world
2  9  10  11  12     foo

In [5]:
!cat ../examples/ex2.csv

1,2,3,4,hello
5,6,7,8,world
9,10,11,12,foo

In [6]:
pd.read_csv("../examples/ex2.csv", header= None)

   0   1   2   3      4
0  1   2   3   4  hello
1  5   6   7   8  world
2  9  10  11  12    foo

In [7]:
pd.read_csv("../examples/ex2.csv", names=["a", "b", "c", "d", "message"])

   a   b   c   d message
0  1   2   3   4   hello
1  5   6   7   8   world
2  9  10  11  12     foo

In [8]:
names = ["a", "b", "c", "d", "message"]
pd.read_csv("../examples/ex2.csv" , names = names , index_col= "message")

         a   b   c   d
message
hello    1   2   3   4
world    5   6   7   8
foo      9  10  11  12

In [9]:
!cat ../examples/csv_mindex.csv

key1,key2,value1,value2
one,a,1,2
one,b,3,4
one,c,5,6
one,d,7,8
two,a,9,10
two,b,11,12
two,c,13,14
two,d,15,16

In [10]:
parsed = pd.read_csv("../examples/csv_mindex.csv" , index_col= ["key1" , "key2"])
parsed

           value1  value2
key1 key2
one  a          1       2
     b          3       4
     c          5       6
     d          7       8
two  a          9      10
     b         11      12
     c         13      14
     d         15      16

In [11]:
!cat ../examples/ex3.txt

            A         B         C
aaa -0.264438 -1.026059 -0.619500
bbb  0.927272  0.302904 -0.032399
ccc -0.264273 -0.386314 -0.217601
ddd -0.871858 -0.348382  1.100491

In [12]:
result = pd.read_csv("../examples/ex3.txt", sep="\s+")
result

            A         B         C
aaa -0.264438 -1.026059 -0.619500
bbb  0.927272  0.302904 -0.032399
ccc -0.264273 -0.386314 -0.217601
ddd -0.871858 -0.348382  1.100491

In [13]:
!cat ../examples/ex4.csv

# hey!
a,b,c,d,message
# just wanted to make things more difficult for you
# who reads CSV files with computers, anyway?
1,2,3,4,hello
5,6,7,8,world
9,10,11,12,foo

In [14]:
pd.read_csv("../examples/ex4.csv", skiprows= [0,2,3])

   a   b   c   d message
0  1   2   3   4   hello
1  5   6   7   8   world
2  9  10  11  12     foo

In [15]:
!cat ../examples/ex5.csv

something,a,b,c,d,message
one,1,2,3,4,NA
two,5,6,,8,world
three,9,10,11,12,foo

In [16]:
result =pd.read_csv("../examples/ex5.csv")

In [17]:
result

  something  a   b     c   d message
0       one  1   2   3.0   4     NaN
1       two  5   6   NaN   8   world
2     three  9  10  11.0  12     foo

In [18]:
pd.isna(result)

   something      a      b      c      d  message
0      False  False  False  False  False     True
1      False  False  False   True  False    False
2      False  False  False  False  False    False

In [19]:
result = pd.read_csv("../examples/ex5.csv", na_values=["NULL"])
result

  something  a   b     c   d message
0       one  1   2   3.0   4     NaN
1       two  5   6   NaN   8   world
2     three  9  10  11.0  12     foo

In [20]:
result = pd.read_csv("../examples/ex5.csv", keep_default_na= False)
result

  something  a   b   c   d message
0       one  1   2   3   4      NA
1       two  5   6       8   world
2     three  9  10  11  12     foo

In [21]:
result.isna()

   something      a      b      c      d  message
0      False  False  False  False  False    False
1      False  False  False  False  False    False
2      False  False  False  False  False    False

In [22]:
result3 = pd.read_csv("../examples/ex5.csv", keep_default_na=False, na_values=["NA"])
result3

  something  a   b   c   d message
0       one  1   2   3   4     NaN
1       two  5   6       8   world
2     three  9  10  11  12     foo

In [23]:
result3.isna()

   something      a      b      c      d  message
0      False  False  False  False  False     True
1      False  False  False  False  False    False
2      False  False  False  False  False    False

In [24]:
sentinels = {"message": ["foo", "NA"], "something": ["two"]}
pd.read_csv("../examples/ex5.csv", keep_default_na= False , na_values= sentinels)

  something  a   b   c   d message
0       one  1   2   3   4     NaN
1       NaN  5   6       8   world
2     three  9  10  11  12     NaN

### Some pandas.read_csv function arguments

| Argument | Description |
| :--- | :--- |
| `path` | String indicating filesystem location, URL, or file-like object. |
| `sep` or `delimiter` | Character sequence or regular expression to use to split fields in each row. |
| `header` | Row number to use as column names; defaults to 0 (first row), but should be `None` if there is no header row. |
| `index_col` | Column numbers or names to use as the row index in the result; can be a single name/number or a list of them for a hierarchical index. |
| `names` | List of column names for result. |
| `skiprows` | Number of rows at beginning of file to ignore or list of row numbers (starting from 0) to skip. |
| `na_values` | Sequence of values to replace with NA. They are added to the default list unless `keep_default_na=False` is passed. |
| `keep_default_na` | Whether to use the default NA value list or not (True by default). |
| `comment` | Character(s) to split comments off the end of lines. |
| `parse_dates` | Attempt to parse data to datetime; False by default. If True, will attempt to parse all columns. Otherwise, can specify a list of column numbers or names to parse. If element of list is tuple or list, will combine multiple columns together and parse to date (e.g., if date/time split across two columns). |
| `keep_date_col` | If joining columns to parse date, keep the joined columns; False by default. |
| `converters` | Dictionary containing column number or name mapping to functions (e.g., `{"foo": f}` would apply the function f to all values in the "foo" column). |
| `dayfirst` | When parsing potentially ambiguous dates, treat as international format (e.g., 7/6/2012 -> June 7, 2012); False by default. |
| `date_parser` | Function to use to parse dates. |
| `nrows` | Number of rows to read from beginning of file (not counting the header). |
| `iterator` | Return a `TextFileReader` object for reading the file piecemeal. This object can also be used with the `with` statement. |
| `chunksize` | For iteration, size of file chunks. |
| `skip_footer` | Number of lines to ignore at end of file. |
| `verbose` | Print various parsing information, like the time spent in each stage of the file conversion and memory use information. |
| `encoding` | Text encoding (e.g., `"utf-8"` for UTF-8 encoded text). Defaults to `"utf-8"` if None. |
| `squeeze` | If the parsed data contains only one column, return a Series. |
| `thousands` | Separator for thousands (e.g., `","` or `"."`); default is None. |
| `decimal` | Decimal separator in numbers (e.g., `"."` or `","`); default is `"."`. |
| `engine` | CSV parsing and conversion engine to use; can be one of `"c"`, `"python"`, or `"pyarrow"`. The default is `"c"`, though the newer `"pyarrow"` engine can parse some files much faster. The `"python"` engine is slower but supports some features that the other engines do not. |

## Reading Text Files in Pieces

In [25]:
pd.options.display.max_rows = 10 #changing the display settings

In [26]:
result = pd.read_csv("../examples/ex6.csv")
result # it will show 10 rows as set previously

           one       two     three      four key
0     0.467976 -0.038649 -0.295344 -1.824726   L
1    -0.358893  1.404453  0.704965 -0.200638   B
2    -0.501840  0.659254 -0.421691 -0.057688   G
3     0.204886  1.074134  1.388361 -0.982404   R
4     0.354628 -0.133116  0.283763 -0.837063   Q
...        ...       ...       ...       ...  ..
9995  2.311896 -0.417070 -1.409599 -0.515821   L
9996 -0.479893 -0.650419  0.745152 -0.646038   E
9997  0.523331  0.787112  0.486066  1.093156   K
9998 -0.362559  0.598894 -1.843201  0.887292   G
9999 -0.096376 -1.012999 -0.657431 -0.573315   0

[10000 rows x 5 columns]

In [27]:
pd.read_csv("../examples/ex6.csv" , nrows = 5 ) # you can also specify this way

        one       two     three      four key
0  0.467976 -0.038649 -0.295344 -1.824726   L
1 -0.358893  1.404453  0.704965 -0.200638   B
2 -0.501840  0.659254 -0.421691 -0.057688   G
3  0.204886  1.074134  1.388361 -0.982404   R
4  0.354628 -0.133116  0.283763 -0.837063   Q

In [28]:
chunker = pd.read_csv("../examples/ex6.csv" , chunksize = 1000 )
chunker

In [29]:
tot = pd.Series()

for piece in chunker:
    tot = tot.add( piece["key"].value_counts() , fill_value= 0 )
    
tot

key
0    151
1    146
2    152
3    162
4    171
    ...
V    328
W    305
X    364
Y    314
Z    288
Length: 36, dtype: object

## Writing Data to Text Format

In [30]:
data = pd.read_csv("../examples/ex5.csv")

In [31]:
data.to_csv("../examples/out.csv") #writing in another file

In [32]:
!cat ../examples/out.csv

,something,a,b,c,d,message
0,one,1,2,3.0,4,
1,two,5,6,,8,world
2,three,9,10,11.0,12,foo

In [33]:
import sys # to show the output in the console without creating another file

In [34]:
data.to_csv(sys.stdout , sep = '|')

|something|a|b|c|d|message
0|one|1|2|3.0|4|
1|two|5|6||8|world
2|three|9|10|11.0|12|foo

In [35]:
data.to_csv(sys.stdout , sep = '|' , na_rep= "Null") # the missing values show as empty strings . we set them to null for them to show

|something|a|b|c|d|message
0|one|1|2|3.0|4|Null
1|two|5|6|Null|8|world
2|three|9|10|11.0|12|foo

In [36]:
data.to_csv(sys.stdout , index = False , header = False )

one,1,2,3.0,4,
two,5,6,,8,world
three,9,10,11.0,12,foo

In [37]:
data.to_csv(sys.stdout, index=False, columns=["a", "b", "c"])

a,b,c
1,2,3.0
5,6,
9,10,11.0

## Working with Other Delimited Formats

In [38]:
!cat ../examples/ex7.csv

"a","b","c"
"1","2","3"
"1","2","3"

In [40]:
import csv
f = open("../examples/ex7.csv")
reader = csv.reader(f)
for line in reader:
    print(line)

['a', 'b', 'c']
['1', '2', '3']
['1', '2', '3']

In [41]:
f.close()

In [43]:
with open("../examples/ex7.csv") as f:
    lines = list(csv.reader(f))

In [44]:
header, values = lines[0], lines[1:]
data_dict = {h: v for h, v in zip(header, zip(*values))}
data_dict

{'a': ('1', '1'), 'b': ('2', '2'), 'c': ('3', '3')}

In [46]:
f = open("../examples/ex7.csv")
class my_dialect(csv.Dialect):
    lineterminator = "\n"
    delimiter = ";"
    quotechar = '"'
    quoting = csv.QUOTE_MINIMAL

reader = csv.reader(f, dialect=my_dialect)

In [47]:
reader = csv.reader(f, delimiter="|")

### CSV dialect options

| Argument | Description |
| :--- | :--- |
| `delimiter` | One-character string to separate fields; defaults to `","`. |
| `lineterminator` | Line terminator for writing; defaults to `"\r\n"`. Reader ignores this and recognizes cross-platform line terminators. |
| `quotechar` | Quote character for fields with special characters (like a delimiter); default is `'"'`. |
| `quoting` | Quoting convention. Options include `csv.QUOTE_ALL` (quote all fields), `csv.QUOTE_MINIMAL` (only fields with special characters like the delimiter), `csv.QUOTE_NONNUMERIC`, and `csv.QUOTE_NONE` (no quoting). See Python's documentation for full details. Defaults to `QUOTE_MINIMAL`. |
| `skipinitialspace` | Ignore whitespace after each delimiter; default is `False`. |
| `doublequote` | How to handle quoting character inside a field; if `True`, it is doubled (see online documentation for full detail and behavior). |
| `escapechar` | String to escape the delimiter if quoting is set to `csv.QUOTE_NONE`; disabled by default. |

In [ ]:
with open("mydata.csv", "w") as f:
    writer = csv.writer(f, dialect=my_dialect)
    writer.writerow(("one", "two", "three"))
    writer.writerow(("1", "2", "3"))
    writer.writerow(("4", "5", "6"))
    writer.writerow(("7", "8", "9"))

## JSON Data