In [2]:
import numpy as np 
import pandas as pd 
from pandas import Series, DataFrame

## DataFrame

In [3]:
data = {"state": ["Ohio", "Ohio", "Ohio", "Nevada", "Nevada", "Nevada"],
"year": [2000, 2001, 2002, 2001, 2002, 2003],
"pop": [1.5, 1.7, 3.6, 2.4, 2.9, 3.2]}

frame = pd.DataFrame(data) # we can only use DataFrame instead of pd.DataFrame because we have imported it from pandas
frame

    state  year  pop
0    Ohio  2000  1.5
1    Ohio  2001  1.7
2    Ohio  2002  3.6
3  Nevada  2001  2.4
4  Nevada  2002  2.9
5  Nevada  2003  3.2

In [4]:
frame.head() #selects only the first 5 rows of the data frame

    state  year  pop
0    Ohio  2000  1.5
1    Ohio  2001  1.7
2    Ohio  2002  3.6
3  Nevada  2001  2.4
4  Nevada  2002  2.9

In [5]:
frame.tail() #selects only the last 5 rows of the data frame

    state  year  pop
1    Ohio  2001  1.7
2    Ohio  2002  3.6
3  Nevada  2001  2.4
4  Nevada  2002  2.9
5  Nevada  2003  3.2

In [6]:
pd.DataFrame( data , columns =[ "year" , "state" , "pop"]) # we can also specify the order of the columns by using the columns parameter. If we do not specify the order, it will be in the order of the keys in the data dictionary. If we specify a column that is not in the data dictionary, it will be filled with NaN values.

   year   state  pop
0  2000    Ohio  1.5
1  2001    Ohio  1.7
2  2002    Ohio  3.6
3  2001  Nevada  2.4
4  2002  Nevada  2.9
5  2003  Nevada  3.2

In [7]:
frame.columns # to get the column names of the data frame

Index(['state', 'year', 'pop'], dtype='object')

In [8]:
frame["year"]

0    2000
1    2001
2    2002
3    2001
4    2002
5    2003
Name: year, dtype: int64

In [9]:
frame2 = pd.DataFrame(data, columns=["year", "state", "pop", "debt"]) # if we add a column that is not in the data dictionary, it will be filled with NaN values.
frame2

   year   state  pop debt
0  2000    Ohio  1.5  NaN
1  2001    Ohio  1.7  NaN
2  2002    Ohio  3.6  NaN
3  2001  Nevada  2.4  NaN
4  2002  Nevada  2.9  NaN
5  2003  Nevada  3.2  NaN

In [10]:
frame2.loc[1]

year     2001
state    Ohio
pop       1.7
debt      NaN
Name: 1, dtype: object

In [11]:
frame2["debt"] = 16.5 # we can also add a column to the data frame by using the column name as the key and the values as the value. If we add a column that is not in the data dictionary, it will be filled with NaN values.
frame2

   year   state  pop  debt
0  2000    Ohio  1.5  16.5
1  2001    Ohio  1.7  16.5
2  2002    Ohio  3.6  16.5
3  2001  Nevada  2.4  16.5
4  2002  Nevada  2.9  16.5
5  2003  Nevada  3.2  16.5

In [12]:
frame2["debt"] = np.arange(6.)
frame2

   year   state  pop  debt
0  2000    Ohio  1.5   0.0
1  2001    Ohio  1.7   1.0
2  2002    Ohio  3.6   2.0
3  2001  Nevada  2.4   3.0
4  2002  Nevada  2.9   4.0
5  2003  Nevada  3.2   5.0

In [13]:
frame2["eastern"] = frame2["state"] == "Ohio"
frame2

   year   state  pop  debt  eastern
0  2000    Ohio  1.5   0.0     True
1  2001    Ohio  1.7   1.0     True
2  2002    Ohio  3.6   2.0     True
3  2001  Nevada  2.4   3.0    False
4  2002  Nevada  2.9   4.0    False
5  2003  Nevada  3.2   5.0    False

In [14]:
del frame2["eastern"] # we can also delete a column from the data frame by using the del keyword and the column name as the key. If we delete a column that is not in the data frame, it will raise a KeyError.
frame2

   year   state  pop  debt
0  2000    Ohio  1.5   0.0
1  2001    Ohio  1.7   1.0
2  2002    Ohio  3.6   2.0
3  2001  Nevada  2.4   3.0
4  2002  Nevada  2.9   4.0
5  2003  Nevada  3.2   5.0

In [15]:
populations = {"Ohio": {2000: 1.5, 2001: 1.7, 2002: 3.6},
    "Nevada": {2001: 2.4, 2002: 2.9}}
frame3 = pd.DataFrame(populations)
frame3

      Ohio  Nevada
2000   1.5     NaN
2001   1.7     2.4
2002   3.6     2.9

In [16]:
frame3.T # to transpose the data frame

        2000  2001  2002
Ohio     1.5   1.7   3.6
Nevada   NaN   2.4   2.9

In [17]:
frame3

      Ohio  Nevada
2000   1.5     NaN
2001   1.7     2.4
2002   3.6     2.9

In [19]:
frame3.index.name = "year"
frame3.columns.name = "state"
frame3

state  Ohio  Nevada
year
2000    1.5     NaN
2001    1.7     2.4
2002    3.6     2.9

In [20]:
frame3.to_numpy() # to convert the data frame to a numpy array. The index and column labels are not included in the output.

array([[1.5, nan],
       [1.7, 2.4],
       [3.6, 2.9]])

## Index Objects

In [21]:
obj = pd.Series(np.arange(3), index=["a", "b", "c"])
obj

a    0
b    1
c    2
dtype: int64

In [22]:
index = obj.index
index

Index(['a', 'b', 'c'], dtype='object')

In [24]:
index[1:]

Index(['b', 'c'], dtype='object')

In [25]:
frame3

state  Ohio  Nevada
year
2000    1.5     NaN
2001    1.7     2.4
2002    3.6     2.9

In [26]:
frame3.columns

Index(['Ohio', 'Nevada'], dtype='object', name='state')

In [31]:
2001 in frame3

False

In [32]:
2001 in frame3.index

True

In [33]:
pd.Index(["foo", "foo", "bar", "bar"]) # pandas index can contain duplicate values. It is not a set. It is a sequence of labels.

Index(['foo', 'foo', 'bar', 'bar'], dtype='object')

### Some Index methods and properties

| Method/Property | Description |
| :--- | :--- |
| `append()` | Concatenate with additional Index objects, producing a new Index |
| `difference()` | Compute set difference as an Index |
| `intersection()` | Compute set intersection |
| `union()` | Compute set union |
| `isin()` | Compute Boolean array indicating whether each value is contained in the passed collection |
| `delete()` | Compute new Index with element at Index $i$ deleted |
| `drop()` | Compute new Index by deleting passed values |
| `insert()` | Compute new Index by inserting element at Index $i$ |
| `is_monotonic` | Returns `True` if each element is greater than or equal to the previous element |
| `is_unique` | Returns `True` if the Index has no duplicate values |
| `unique()` | Compute the array of unique values in the Index |