In [2]:
import numpy as np 
import pandas as pd

## Reindexing

In [3]:
obj = pd.Series([4.5, 7.2, -5.3, 3.6], index=["d", "b", "a", "c"])
obj

d    4.5
b    7.2
a   -5.3
c    3.6
dtype: float64

In [4]:
obj2 = obj.reindex(["a", "b", "c", "d", "e"])
obj2

a   -5.3
b    7.2
c    3.6
d    4.5
e    NaN
dtype: float64

In [5]:
obj3 = pd.Series(["blue", "purple", "yellow"], index=[0, 2, 4])
obj3

0      blue
2    purple
4    yellow
dtype: object

In [6]:
obj3.reindex(range(6), method="ffill")

0      blue
1      blue
2    purple
3    purple
4    yellow
5    yellow
dtype: object

In [7]:
frame = pd.DataFrame( np.arange(9) . reshape((3,3)) , index = [ 'a' , 'c' , 'd' ] , columns = ["Ohio", "Texas", "California"])
frame

   Ohio  Texas  California
a     0      1           2
c     3      4           5
d     6      7           8

In [8]:
frame2 = frame.reindex(index=["a", "b", "c", "d"])
frame2

   Ohio  Texas  California
a   0.0    1.0         2.0
b   NaN    NaN         NaN
c   3.0    4.0         5.0
d   6.0    7.0         8.0

In [9]:
states = ["Texas", "Utah", "California"]
frame.reindex( columns = states )

   Texas  Utah  California
a      1   NaN           2
c      4   NaN           5
d      7   NaN           8

In [10]:
frame.reindex(states, axis="columns") #does the same the thing as the prev one

   Texas  Utah  California
a      1   NaN           2
c      4   NaN           5
d      7   NaN           8

### reindex function arguments

| Argument | Description |
| :--- | :--- |
| `labels` | New sequence to use as an index. Can be Index instance or any other sequence-like Python data structure. An Index will be used exactly as is without any copying. |
| `index` | Use the passed sequence as the new index labels. |
| `columns` | Use the passed sequence as the new column labels. |
| `axis` | The axis to reindex, whether "index" (rows) or "columns". The default is "index". You can alternately do `reindex(index=new_labels)` or `reindex(columns=new_labels)`. |
| `method` | Interpolation (fill) method; `"ffill"` fills forward, while `"bfill"` fills backward. |
| `fill_value` | Substitute value to use when introducing missing data by reindexing. Use `fill_value="missing"` (the default behavior) when you want absent labels to have null values in the result. |
| `limit` | When forward filling or backfilling, the maximum size gap (in number of elements) to fill. |
| `tolerance` | When forward filling or backfilling, the maximum size gap (in absolute numeric distance) to fill for inexact matches. |
| `level` | Match simple Index on level of MultiIndex; otherwise select subset of. |
| `copy` | If `True`, always copy underlying data even if the new index is equivalent to the old index; if `False`, do not copy the data when the indexes are equivalent. |

## Dropping Entries from an Axis

In [11]:
obj = pd.Series(np.arange(5.), index=["a", "b", "c", "d", "e"])
obj2 = obj.drop("a")
obj2

b    1.0
c    2.0
d    3.0
e    4.0
dtype: float64

In [12]:
obj.drop("c")

a    0.0
b    1.0
d    3.0
e    4.0
dtype: float64

In [13]:
data = pd.DataFrame(np.arange(16).reshape((4, 4)),
    index=["Ohio", "Colorado", "Utah", "New York"],
    columns=["one", "two", "three", "four"])
data

          one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

In [14]:
data.drop( index = ["Utah"] )

          one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7
New York   12   13     14    15

In [15]:
data.drop( columns = ["two"])

          one  three  four
Ohio        0      2     3
Colorado    4      6     7
Utah        8     10    11
New York   12     14    15

In [16]:
data.drop( "two" , axis = 1 )

          one  three  four
Ohio        0      2     3
Colorado    4      6     7
Utah        8     10    11
New York   12     14    15

## Indexing, Selection, and Filtering

In [17]:
obj = pd.Series(np.arange(4.), index=["a", "b", "c", "d"])
obj

a    0.0
b    1.0
c    2.0
d    3.0
dtype: float64

In [18]:
obj["b"]

np.float64(1.0)

In [19]:
obj[1]

C:\Users\Rasif Rohan\AppData\Local\Temp\ipykernel_5904\2469632899.py:1: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  obj[1]

np.float64(1.0)

In [20]:
obj[2:4]

c    2.0
d    3.0
dtype: float64

In [21]:
obj[obj < 2]

a    0.0
b    1.0
dtype: float64

In [22]:
obj.loc[["a", "b", "c"]] #loc operator indexes exclusively with labels

a    0.0
b    1.0
c    2.0
dtype: float64

In [23]:
obj.iloc[[1, 2, 3]] # iloc operator indexes exclusively with integers

b    1.0
c    2.0
d    3.0
dtype: float64

In [24]:
obj2 = pd.Series([1, 2, 3], index=["a", "b", "c"])
obj2

a    1
b    2
c    3
dtype: int64

In [25]:
obj2.loc["b":"c"]

b    2
c    3
dtype: int64

In [26]:
obj2.loc["b" : "c" ] = 5 
obj2

a    1
b    5
c    5
dtype: int64

In [27]:
data = pd.DataFrame(np.arange(16).reshape((4, 4)),
    index=["Ohio", "Colorado", "Utah", "New York"],
    columns=["one", "two", "three", "four"])
data

          one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

In [28]:
data[["three"  , "four"]]

          three  four
Ohio          2     3
Colorado      6     7
Utah         10    11
New York     14    15

In [29]:
data[:2]

          one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7

In [30]:
data[data["three"] > 5]

          one  two  three  four
Colorado    4    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

### Selection on DataFrame with loc and iloc

In [31]:
data

          one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

In [32]:
data.loc["Colorado"]

one      4
two      5
three    6
four     7
Name: Colorado, dtype: int64

In [33]:
data.loc[["Colorado" ,"Utah"]]

          one  two  three  four
Colorado    4    5      6     7
Utah        8    9     10    11

In [34]:
data.loc["Colorado" ,["two" , "three"]]

two      5
three    6
Name: Colorado, dtype: int64

In [35]:
data.iloc[2]

one       8
two       9
three    10
four     11
Name: Utah, dtype: int64

In [36]:
data.iloc[[2,1]]

          one  two  three  four
Utah        8    9     10    11
Colorado    4    5      6     7

In [37]:
data.iloc[[2,1], [3,1]]

          four  two
Utah        11    9
Colorado     7    5

In [38]:
data.loc[:"Utah" , :"two"]

          one  two
Ohio        0    1
Colorado    4    5
Utah        8    9

In [39]:
data.iloc[:, :3] [ data["three"]>5 ]

          one  two  three
Colorado    4    5      6
Utah        8    9     10
New York   12   13     14

### Indexing options with DataFrame

| Type | Notes |
| :--- | :--- |
| `df[column]` | Select single column or sequence of columns from the DataFrame; special case conveniences: Boolean array (filter rows), slice (slice rows), or Boolean DataFrame (set values based on some criterion) |
| `df.loc[rows]` | Select single row or subset of rows from the DataFrame by label |
| `df.loc[:, cols]` | Select single column or subset of columns by label |
| `df.loc[rows, cols]` | Select both row(s) and column(s) by label |
| `df.iloc[rows]` | Select single row or subset of rows from the DataFrame by integer position |
| `df.iloc[:, cols]` | Select single column or subset of columns by integer position |
| `df.iloc[rows, cols]` | Select both row(s) and column(s) by integer position |
| `df.at[row, col]` | Select a single scalar value by row and column label |
| `df.iat[row, col]` | Select a single scalar value by row and column position (integers) |
| `reindex` method | Select either rows or columns by labels |

## Arithmetic and Data Alignment

In [40]:
s1 = pd.Series([7.3, -2.5, 3.4, 1.5], index=["a", "c", "d", "e"])
s2 = pd.Series([-2.1, 3.6, -1.5, 4, 3.1],index=["a", "c", "e", "f", "g"])

In [41]:
s1

a    7.3
c   -2.5
d    3.4
e    1.5
dtype: float64

In [42]:
s2

a   -2.1
c    3.6
e   -1.5
f    4.0
g    3.1
dtype: float64

In [43]:
s1+s2

a    5.2
c    1.1
d    NaN
e    0.0
f    NaN
g    NaN
dtype: float64

In [44]:
df1 = pd.DataFrame(np.arange(9.).reshape((3, 3)), columns=list("bcd"),
    index=["Ohio", "Texas", "Colorado"])
df2 = pd.DataFrame(np.arange(12.).reshape((4, 3)), columns=list("bde"),
    index=["Utah", "Ohio", "Texas", "Oregon"])

In [45]:
df1

            b    c    d
Ohio      0.0  1.0  2.0
Texas     3.0  4.0  5.0
Colorado  6.0  7.0  8.0

In [46]:
df2

          b     d     e
Utah    0.0   1.0   2.0
Ohio    3.0   4.0   5.0
Texas   6.0   7.0   8.0
Oregon  9.0  10.0  11.0

In [47]:
df1+df2

            b   c     d   e
Colorado  NaN NaN   NaN NaN
Ohio      3.0 NaN   6.0 NaN
Oregon    NaN NaN   NaN NaN
Texas     9.0 NaN  12.0 NaN
Utah      NaN NaN   NaN NaN

### Arithmetic methods with fill values

In [48]:
df1 = pd.DataFrame( np.arange(12).reshape((3,4)) , columns = list("abcd"))
df2 = pd.DataFrame(np.arange(20.).reshape((4, 5)),columns = list("abcde"))

In [49]:
df1

   a  b   c   d
0  0  1   2   3
1  4  5   6   7
2  8  9  10  11

In [50]:
df2

      a     b     c     d     e
0   0.0   1.0   2.0   3.0   4.0
1   5.0   6.0   7.0   8.0   9.0
2  10.0  11.0  12.0  13.0  14.0
3  15.0  16.0  17.0  18.0  19.0

In [51]:
df1+df2

      a     b     c     d   e
0   0.0   2.0   4.0   6.0 NaN
1   9.0  11.0  13.0  15.0 NaN
2  18.0  20.0  22.0  24.0 NaN
3   NaN   NaN   NaN   NaN NaN

In [52]:
df1.add(df2, fill_value = 0 )

      a     b     c     d     e
0   0.0   2.0   4.0   6.0   4.0
1   9.0  11.0  13.0  15.0   9.0
2  18.0  20.0  22.0  24.0  14.0
3  15.0  16.0  17.0  18.0  19.0

In [53]:
df1.rdiv(1)

       a         b         c         d
0    inf  1.000000  0.500000  0.333333
1  0.250  0.200000  0.166667  0.142857
2  0.125  0.111111  0.100000  0.090909

### Flexible arithmetic methods

| Method | Description |
| :--- | :--- |
| `add`, `radd` | Methods for addition (+) |
| `sub`, `rsub` | Methods for subtraction (-) |
| `div`, `rdiv` | Methods for division (/) |
| `floordiv`, `rfloordiv` | Methods for floor division (//) |
| `mul`, `rmul` | Methods for multiplication (*) |
| `pow`, `rpow` | Methods for exponentiation (**) |

### Operations between DataFrame and Series

In [54]:
frame = pd.DataFrame(np.arange(12.).reshape((4, 3)),
    columns=list("bde"),
    index=["Utah", "Ohio", "Texas", "Oregon"])
frame

          b     d     e
Utah    0.0   1.0   2.0
Ohio    3.0   4.0   5.0
Texas   6.0   7.0   8.0
Oregon  9.0  10.0  11.0

In [56]:
series = frame.iloc[0]
series

b    0.0
d    1.0
e    2.0
Name: Utah, dtype: float64

In [57]:
frame - series

          b    d    e
Utah    0.0  0.0  0.0
Ohio    3.0  3.0  3.0
Texas   6.0  6.0  6.0
Oregon  9.0  9.0  9.0

In [59]:
series2= pd.Series(np.arange(3), index = list("bef"))
series2

b    0
e    1
f    2
dtype: int64

In [60]:
frame + series2

          b   d     e   f
Utah    0.0 NaN   3.0 NaN
Ohio    3.0 NaN   6.0 NaN
Texas   6.0 NaN   9.0 NaN
Oregon  9.0 NaN  12.0 NaN

In [61]:
series3 = frame["d"]
series3

Utah       1.0
Ohio       4.0
Texas      7.0
Oregon    10.0
Name: d, dtype: float64

In [63]:
frame.sub( series3 , axis = "index")

          b    d    e
Utah   -1.0  0.0  1.0
Ohio   -1.0  0.0  1.0
Texas  -1.0  0.0  1.0
Oregon -1.0  0.0  1.0

### Function Application and Mapping

In [64]:
frame = pd.DataFrame(np.random.standard_normal((4, 3)),
    columns=list("bde"),
    index=["Utah", "Ohio", "Texas", "Oregon"])
frame

               b         d         e
Utah   -0.119733 -0.463236  0.199447
Ohio    1.590679  0.241981 -1.024506
Texas   0.848164 -0.332480 -0.719993
Oregon -0.331236 -1.094223  0.045054

In [65]:
np.abs(frame)

               b         d         e
Utah    0.119733  0.463236  0.199447
Ohio    1.590679  0.241981  1.024506
Texas   0.848164  0.332480  0.719993
Oregon  0.331236  1.094223  0.045054

In [66]:
def f1(x):
    return x.max() - x.min()

frame.apply(f1)

b    1.921915
d    1.336204
e    1.223952
dtype: float64

In [69]:
frame.apply(f1, axis = "columns")

Utah      0.662682
Ohio      2.615185
Texas     1.568157
Oregon    1.139278
dtype: float64

In [70]:
def f2(x):
    return pd.Series([x.min(), x.max()], index=["min", "max"])

frame.apply(f2)

            b         d         e
min -0.331236 -1.094223 -1.024506
max  1.590679  0.241981  0.199447

In [72]:
def my_format(x):
    return f"{x:.2f}"

frame.applymap(my_format)

C:\Users\Rasif Rohan\AppData\Local\Temp\ipykernel_5904\2705683181.py:4: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  frame.applymap(my_format)

            b      d      e
Utah    -0.12  -0.46   0.20
Ohio     1.59   0.24  -1.02
Texas    0.85  -0.33  -0.72
Oregon  -0.33  -1.09   0.05

### Sorting and Ranking

In [73]:
obj = pd.Series( np.arange(4) , index = list("dabc"))
obj

d    0
a    1
b    2
c    3
dtype: int64

In [74]:
obj.sort_index()

a    1
b    2
c    3
d    0
dtype: int64

In [75]:
frame = pd.DataFrame(np.arange(8).reshape((2, 4)),
    index=["three", "one"],
    columns=["d", "a", "b", "c"])
frame

       d  a  b  c
three  0  1  2  3
one    4  5  6  7

In [76]:
frame.sort_index()

       d  a  b  c
one    4  5  6  7
three  0  1  2  3

In [77]:
frame.sort_index(axis = "columns")

       a  b  c  d
three  1  2  3  0
one    5  6  7  4

In [ ]:
frame.sort_index( axis = "columns" , ascending = False) # will sort in a descending order

       d  c  b  a
three  0  3  2  1
one    4  7  6  5

In [79]:
obj = pd.Series([4, 7, -3, 2])
obj

0    4
1    7
2   -3
3    2
dtype: int64

In [ ]:
obj.sort_values() #sorting by the values

2   -3
3    2
0    4
1    7
dtype: int64

In [81]:
obj = pd.Series([4, np.nan, 7, np.nan, -3, 2])
obj

0    4.0
1    NaN
2    7.0
3    NaN
4   -3.0
5    2.0
dtype: float64

In [ ]:
obj.sort_values() #nan values will appear at the bottom

4   -3.0
5    2.0
0    4.0
2    7.0
1    NaN
3    NaN
dtype: float64

In [ ]:
obj.sort_values(na_position = "first") #puts the nan values first

1    NaN
3    NaN
4   -3.0
5    2.0
0    4.0
2    7.0
dtype: float64

In [85]:
frame = pd.DataFrame({"b": [4, 7, -3, 2], "a": [0, 1, 0, 1]})
frame

   b  a
0  4  0
1  7  1
2 -3  0
3  2  1

In [86]:
frame.sort_values("b")

   b  a
2 -3  0
3  2  1
0  4  0
1  7  1

In [87]:
frame.sort_values(["a","b"])

   b  a
2 -3  0
0  4  0
3  2  1
1  7  1

In [88]:
obj = pd.Series([7, -5, 7, 4, 2, 0, 4])
obj

0    7
1   -5
2    7
3    4
4    2
5    0
6    4
dtype: int64

In [ ]:
obj.rank() # basically saying the rank of the value in that index . if the value is repeated then its average is put in there

0    6.5
1    1.0
2    6.5
3    4.5
4    3.0
5    2.0
6    4.5
dtype: float64

In [ ]:
obj.rank(method = "first") #ccording to the order in which they’re observed in the data

0    6.0
1    1.0
2    7.0
3    4.0
4    3.0
5    2.0
6    5.0
dtype: float64

In [91]:
obj.rank(ascending = False)

0    1.5
1    7.0
2    1.5
3    3.5
4    5.0
5    6.0
6    3.5
dtype: float64

In [92]:
frame = pd.DataFrame({"b": [4.3, 7, -3, 2], "a": [0, 1, 0, 1],"c": [-2, 5, 8, -2.5]})
frame

     b  a    c
0  4.3  0 -2.0
1  7.0  1  5.0
2 -3.0  0  8.0
3  2.0  1 -2.5

In [93]:
frame.rank(axis= "columns")

     b    a    c
0  3.0  2.0  1.0
1  3.0  1.0  2.0
2  1.0  2.0  3.0
3  3.0  2.0  1.0

### Tie-breaking methods with rank

| Method | Description |
| :--- | :--- |
| `"average"` | Default: assign the average rank to each entry in the equal group |
| `"min"` | Use the minimum rank for the whole group |
| `"max"` | Use the maximum rank for the whole group |
| `"first"` | Assign ranks in the order the values appear in the data |
| `"dense"` | Like `method="min"`, but ranks always increase by 1 between groups rather than the number of equal elements in a group |

## Summarizing and Computing Descriptive Statistics

In [94]:
df = pd.DataFrame([[1.4, np.nan], [7.1, -4.5],
    [np.nan, np.nan], [0.75, -1.3]],
    index=["a", "b", "c", "d"],
    columns=["one", "two"])
df

    one  two
a  1.40  NaN
b  7.10 -4.5
c   NaN  NaN
d  0.75 -1.3

In [ ]:
df.sum() #returns a Series containing column sums

one    9.25
two   -5.80
dtype: float64

In [96]:
df.sum(axis="index", skipna=False)

one   NaN
two   NaN
dtype: float64

In [98]:
df.mean(axis = "columns")

a    1.400
b    1.300
c      NaN
d   -0.275
dtype: float64

In [ ]:
df.idxmax() # gives the index of the max element

one    b
two    d
dtype: object

In [102]:
df.describe()

            one       two
count  3.000000  2.000000
mean   3.083333 -2.900000
std    3.493685  2.262742
min    0.750000 -4.500000
25%    1.075000 -3.700000
50%    1.400000 -2.900000
75%    4.250000 -2.100000
max    7.100000 -1.300000

In [103]:
obj = pd.Series(["a", "a", "b", "c"] * 4)
obj

0     a
1     a
2     b
3     c
4     a
5     a
6     b
7     c
8     a
9     a
10    b
11    c
12    a
13    a
14    b
15    c
dtype: object

In [104]:
obj.describe()

count     16
unique     3
top        a
freq       8
dtype: object

### Descriptive and summary statistics

| Method | Description |
| :--- | :--- |
| `count` | Number of non-NA values |
| `describe` | Compute set of summary statistics |
| `min`, `max` | Compute minimum and maximum values |
| `argmin`, `argmax` | Compute index locations (integers) at which minimum or maximum value is obtained, respectively; not available on DataFrame objects |
| `idxmin`, `idxmax` | Compute index labels at which minimum or maximum value is obtained, respectively |
| `quantile` | Compute sample quantile ranging from 0 to 1 (default: 0.5) |
| `sum` | Sum of values |
| `mean` | Mean of values |
| `median` | Arithmetic median (50% quantile) of values |
| `mad` | Mean absolute deviation from mean value |
| `prod` | Product of all values |
| `var` | Sample variance of values |
| `std` | Sample standard deviation of values |
| `skew` | Sample skewness (third moment) of values |
| `kurt` | Sample kurtosis (fourth moment) of values |
| `cumsum` | Cumulative sum of values |
| `cummin`, `cummax` | Cumulative minimum or maximum of values, respectively |
| `cumprod` | Cumulative product of values |
| `diff` | Compute first arithmetic difference (useful for time series) |
| `pct_change` | Compute percent changes |

### Correlation and Covariance

In [107]:
price = pd.read_pickle("../examples/yahoo_price.pkl")
volume = pd.read_pickle("../examples/yahoo_volume.pkl")

In [110]:
returns = price.pct_change()
returns.tail()

                AAPL      GOOG       IBM      MSFT
Date
2016-10-17 -0.000680  0.001837  0.002072 -0.003483
2016-10-18 -0.000681  0.019616 -0.026168  0.007690
2016-10-19 -0.002979  0.007846  0.003583 -0.002255
2016-10-20 -0.000512 -0.005652  0.001719 -0.004867
2016-10-21 -0.003930  0.003011 -0.012474  0.042096

In [111]:
returns["MSFT"].corr( returns["IBM"] )

np.float64(0.4997636114415114)

In [112]:
returns["MSFT"].cov( returns["IBM"] )

np.float64(8.870655479703546e-05)

In [113]:
returns.corr()

          AAPL      GOOG       IBM      MSFT
AAPL  1.000000  0.407919  0.386817  0.389695
GOOG  0.407919  1.000000  0.405099  0.465919
IBM   0.386817  0.405099  1.000000  0.499764
MSFT  0.389695  0.465919  0.499764  1.000000

In [115]:
returns.cov()

          AAPL      GOOG       IBM      MSFT
AAPL  0.000277  0.000107  0.000078  0.000095
GOOG  0.000107  0.000251  0.000078  0.000108
IBM   0.000078  0.000078  0.000146  0.000089
MSFT  0.000095  0.000108  0.000089  0.000215

In [116]:
returns.corrwith(returns["IBM"])

AAPL    0.386817
GOOG    0.405099
IBM     1.000000
MSFT    0.499764
dtype: float64

In [117]:
returns.corrwith(volume)

AAPL   -0.075565
GOOG   -0.007067
IBM    -0.204849
MSFT   -0.092950
dtype: float64

### Unique Values, Value Counts, and Membership

In [118]:
obj = pd.Series(["c", "a", "d", "a", "a", "b", "b", "c", "c"])
obj

0    c
1    a
2    d
3    a
4    a
5    b
6    b
7    c
8    c
dtype: object

In [119]:
obj.unique()

array(['c', 'a', 'd', 'b'], dtype=object)

In [120]:
obj.value_counts()

c    3
a    3
b    2
d    1
Name: count, dtype: int64

In [121]:
obj.isin(["b","c"])

0     True
1    False
2    False
3    False
4    False
5     True
6     True
7     True
8     True
dtype: bool

In [122]:
to_match = pd.Series(["c", "a", "b", "b", "c", "a"])
unique_vals = pd.Series(["c", "b", "a"])
pd.Index(unique_vals).get_indexer(to_match)

array([0, 2, 1, 1, 0, 2])

### Unique, value counts, and set membership methods

| Method | Description |
| :--- | :--- |
| `isin` | Compute a Boolean array indicating whether each Series or DataFrame value is contained in the passed sequence of values |
| `get_indexer` | Compute integer indices for each value in an array into another array of distinct values; helpful for data alignment and join-type operations |
| `unique` | Compute an array of unique values in a Series, returned in the order observed |
| `value_counts` | Return a Series containing unique values as its index and frequencies as its values, ordered count in descending order |

In [123]:
data = pd.DataFrame({"a": [1, 1, 1, 2, 2], "b": [0, 0, 1, 0, 0]})
data

   a  b
0  1  0
1  1  0
2  1  1
3  2  0
4  2  0

In [124]:
data.value_counts() #calculates the occurence of each row

a  b
1  0    2
2  0    2
1  1    1
Name: count, dtype: int64

In [125]:
data = pd.DataFrame({"Qu1": [1, 3, 4, 3, 4],
    "Qu2": [2, 3, 1, 2, 3],
    "Qu3": [1, 5, 2, 4, 4]})
data

   Qu1  Qu2  Qu3
0    1    2    1
1    3    3    5
2    4    1    2
3    3    2    4
4    4    3    4

In [126]:
data["Qu1"].value_counts().sort_values()

Qu1
1    1
3    2
4    2
Name: count, dtype: int64

In [ ]:
data.apply(pd.value_counts).fillna(0) # index become the unique value and the occurences in each column is shown

C:\Users\Rasif Rohan\AppData\Local\Temp\ipykernel_5904\2493099384.py:1: FutureWarning: pandas.value_counts is deprecated and will be removed in a future version. Use pd.Series(obj).value_counts() instead.
  data.apply(pd.value_counts).fillna(0)

   Qu1  Qu2  Qu3
1  1.0  1.0  1.0
2  0.0  2.0  1.0
3  2.0  2.0  0.0
4  2.0  0.0  2.0
5  0.0  0.0  1.0