In [1]:
import numpy as np 
import pandas as pd

## Reindexing

In [2]:
obj = pd.Series([4.5, 7.2, -5.3, 3.6], index=["d", "b", "a", "c"])
obj

d    4.5
b    7.2
a   -5.3
c    3.6
dtype: float64

In [3]:
obj2 = obj.reindex(["a", "b", "c", "d", "e"])
obj2

a   -5.3
b    7.2
c    3.6
d    4.5
e    NaN
dtype: float64

In [4]:
obj3 = pd.Series(["blue", "purple", "yellow"], index=[0, 2, 4])
obj3

0      blue
2    purple
4    yellow
dtype: object

In [5]:
obj3.reindex(range(6), method="ffill")

0      blue
1      blue
2    purple
3    purple
4    yellow
5    yellow
dtype: object

In [6]:
frame = pd.DataFrame( np.arange(9) . reshape((3,3)) , index = [ 'a' , 'c' , 'd' ] , columns = ["Ohio", "Texas", "California"])
frame

   Ohio  Texas  California
a     0      1           2
c     3      4           5
d     6      7           8

In [7]:
frame2 = frame.reindex(index=["a", "b", "c", "d"])
frame2

   Ohio  Texas  California
a   0.0    1.0         2.0
b   NaN    NaN         NaN
c   3.0    4.0         5.0
d   6.0    7.0         8.0

In [8]:
states = ["Texas", "Utah", "California"]
frame.reindex( columns = states )

   Texas  Utah  California
a      1   NaN           2
c      4   NaN           5
d      7   NaN           8

In [9]:
frame.reindex(states, axis="columns") #does the same the thing as the prev one

   Texas  Utah  California
a      1   NaN           2
c      4   NaN           5
d      7   NaN           8

### reindex function arguments

| Argument | Description |
| :--- | :--- |
| `labels` | New sequence to use as an index. Can be Index instance or any other sequence-like Python data structure. An Index will be used exactly as is without any copying. |
| `index` | Use the passed sequence as the new index labels. |
| `columns` | Use the passed sequence as the new column labels. |
| `axis` | The axis to reindex, whether "index" (rows) or "columns". The default is "index". You can alternately do `reindex(index=new_labels)` or `reindex(columns=new_labels)`. |
| `method` | Interpolation (fill) method; `"ffill"` fills forward, while `"bfill"` fills backward. |
| `fill_value` | Substitute value to use when introducing missing data by reindexing. Use `fill_value="missing"` (the default behavior) when you want absent labels to have null values in the result. |
| `limit` | When forward filling or backfilling, the maximum size gap (in number of elements) to fill. |
| `tolerance` | When forward filling or backfilling, the maximum size gap (in absolute numeric distance) to fill for inexact matches. |
| `level` | Match simple Index on level of MultiIndex; otherwise select subset of. |
| `copy` | If `True`, always copy underlying data even if the new index is equivalent to the old index; if `False`, do not copy the data when the indexes are equivalent. |

## Dropping Entries from an Axis

In [10]:
obj = pd.Series(np.arange(5.), index=["a", "b", "c", "d", "e"])
obj2 = obj.drop("a")
obj2

b    1.0
c    2.0
d    3.0
e    4.0
dtype: float64

In [11]:
obj.drop("c")

a    0.0
b    1.0
d    3.0
e    4.0
dtype: float64

In [12]:
data = pd.DataFrame(np.arange(16).reshape((4, 4)),
    index=["Ohio", "Colorado", "Utah", "New York"],
    columns=["one", "two", "three", "four"])
data

          one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

In [13]:
data.drop( index = ["Utah"] )

          one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7
New York   12   13     14    15

In [14]:
data.drop( columns = ["two"])

          one  three  four
Ohio        0      2     3
Colorado    4      6     7
Utah        8     10    11
New York   12     14    15

In [15]:
data.drop( "two" , axis = 1 )

          one  three  four
Ohio        0      2     3
Colorado    4      6     7
Utah        8     10    11
New York   12     14    15

## Indexing, Selection, and Filtering

In [16]:
obj = pd.Series(np.arange(4.), index=["a", "b", "c", "d"])
obj

a    0.0
b    1.0
c    2.0
d    3.0
dtype: float64

In [17]:
obj["b"]

np.float64(1.0)

In [18]:
obj[1]

C:\Users\Rasif Rohan\AppData\Local\Temp\ipykernel_17356\2469632899.py:1: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  obj[1]

np.float64(1.0)

In [19]:
obj[2:4]

c    2.0
d    3.0
dtype: float64

In [20]:
obj[obj < 2]

a    0.0
b    1.0
dtype: float64

In [ ]:
obj.loc[["a", "b", "c"]] #loc operator indexes exclusively with labels

a    0.0
b    1.0
c    2.0
dtype: float64

In [ ]:
obj.iloc[[1, 2, 3]] # iloc operator indexes exclusively with integers

b    1.0
c    2.0
d    3.0
dtype: float64

In [23]:
obj2 = pd.Series([1, 2, 3], index=["a", "b", "c"])
obj2

a    1
b    2
c    3
dtype: int64

In [24]:
obj2.loc["b":"c"]

b    2
c    3
dtype: int64

In [26]:
obj2.loc["b" : "c" ] = 5 
obj2

a    1
b    5
c    5
dtype: int64