In [1]:
import numpy as np 
import pandas as pd

## Reindexing

In [2]:
obj = pd.Series([4.5, 7.2, -5.3, 3.6], index=["d", "b", "a", "c"])
obj

d    4.5
b    7.2
a   -5.3
c    3.6
dtype: float64

In [3]:
obj2 = obj.reindex(["a", "b", "c", "d", "e"])
obj2

a   -5.3
b    7.2
c    3.6
d    4.5
e    NaN
dtype: float64

In [4]:
obj3 = pd.Series(["blue", "purple", "yellow"], index=[0, 2, 4])
obj3

0      blue
2    purple
4    yellow
dtype: object

In [5]:
obj3.reindex(range(6), method="ffill")

0      blue
1      blue
2    purple
3    purple
4    yellow
5    yellow
dtype: object

In [6]:
frame = pd.DataFrame( np.arange(9) . reshape((3,3)) , index = [ 'a' , 'c' , 'd' ] , columns = ["Ohio", "Texas", "California"])
frame

   Ohio  Texas  California
a     0      1           2
c     3      4           5
d     6      7           8

In [7]:
frame2 = frame.reindex(index=["a", "b", "c", "d"])
frame2

   Ohio  Texas  California
a   0.0    1.0         2.0
b   NaN    NaN         NaN
c   3.0    4.0         5.0
d   6.0    7.0         8.0

In [8]:
states = ["Texas", "Utah", "California"]
frame.reindex( columns = states )

   Texas  Utah  California
a      1   NaN           2
c      4   NaN           5
d      7   NaN           8

In [9]:
frame.reindex(states, axis="columns") #does the same the thing as the prev one

   Texas  Utah  California
a      1   NaN           2
c      4   NaN           5
d      7   NaN           8

### reindex function arguments

| Argument | Description |
| :--- | :--- |
| `labels` | New sequence to use as an index. Can be Index instance or any other sequence-like Python data structure. An Index will be used exactly as is without any copying. |
| `index` | Use the passed sequence as the new index labels. |
| `columns` | Use the passed sequence as the new column labels. |
| `axis` | The axis to reindex, whether "index" (rows) or "columns". The default is "index". You can alternately do `reindex(index=new_labels)` or `reindex(columns=new_labels)`. |
| `method` | Interpolation (fill) method; `"ffill"` fills forward, while `"bfill"` fills backward. |
| `fill_value` | Substitute value to use when introducing missing data by reindexing. Use `fill_value="missing"` (the default behavior) when you want absent labels to have null values in the result. |
| `limit` | When forward filling or backfilling, the maximum size gap (in number of elements) to fill. |
| `tolerance` | When forward filling or backfilling, the maximum size gap (in absolute numeric distance) to fill for inexact matches. |
| `level` | Match simple Index on level of MultiIndex; otherwise select subset of. |
| `copy` | If `True`, always copy underlying data even if the new index is equivalent to the old index; if `False`, do not copy the data when the indexes are equivalent. |

## Dropping Entries from an Axis

In [10]:
obj = pd.Series(np.arange(5.), index=["a", "b", "c", "d", "e"])
obj2 = obj.drop("a")
obj2

b    1.0
c    2.0
d    3.0
e    4.0
dtype: float64

In [11]:
obj.drop("c")

a    0.0
b    1.0
d    3.0
e    4.0
dtype: float64

In [12]:
data = pd.DataFrame(np.arange(16).reshape((4, 4)),
    index=["Ohio", "Colorado", "Utah", "New York"],
    columns=["one", "two", "three", "four"])
data

          one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

In [13]:
data.drop( index = ["Utah"] )

          one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7
New York   12   13     14    15

In [14]:
data.drop( columns = ["two"])

          one  three  four
Ohio        0      2     3
Colorado    4      6     7
Utah        8     10    11
New York   12     14    15

In [15]:
data.drop( "two" , axis = 1 )

          one  three  four
Ohio        0      2     3
Colorado    4      6     7
Utah        8     10    11
New York   12     14    15

## Indexing, Selection, and Filtering

In [16]:
obj = pd.Series(np.arange(4.), index=["a", "b", "c", "d"])
obj

a    0.0
b    1.0
c    2.0
d    3.0
dtype: float64

In [17]:
obj["b"]

np.float64(1.0)

In [18]:
obj[1]

C:\Users\Rasif Rohan\AppData\Local\Temp\ipykernel_4732\2469632899.py:1: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  obj[1]

np.float64(1.0)

In [19]:
obj[2:4]

c    2.0
d    3.0
dtype: float64

In [20]:
obj[obj < 2]

a    0.0
b    1.0
dtype: float64

In [21]:
obj.loc[["a", "b", "c"]] #loc operator indexes exclusively with labels

a    0.0
b    1.0
c    2.0
dtype: float64

In [22]:
obj.iloc[[1, 2, 3]] # iloc operator indexes exclusively with integers

b    1.0
c    2.0
d    3.0
dtype: float64

In [23]:
obj2 = pd.Series([1, 2, 3], index=["a", "b", "c"])
obj2

a    1
b    2
c    3
dtype: int64

In [24]:
obj2.loc["b":"c"]

b    2
c    3
dtype: int64

In [25]:
obj2.loc["b" : "c" ] = 5 
obj2

a    1
b    5
c    5
dtype: int64

In [27]:
data = pd.DataFrame(np.arange(16).reshape((4, 4)),
    index=["Ohio", "Colorado", "Utah", "New York"],
    columns=["one", "two", "three", "four"])
data

          one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

In [28]:
data[["three"  , "four"]]

          three  four
Ohio          2     3
Colorado      6     7
Utah         10    11
New York     14    15

In [29]:
data[:2]

          one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7

In [30]:
data[data["three"] > 5]

          one  two  three  four
Colorado    4    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

### Selection on DataFrame with loc and iloc

In [31]:
data

          one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

In [33]:
data.loc["Colorado"]

one      4
two      5
three    6
four     7
Name: Colorado, dtype: int64

In [35]:
data.loc[["Colorado" ,"Utah"]]

          one  two  three  four
Colorado    4    5      6     7
Utah        8    9     10    11

In [36]:
data.loc["Colorado" ,["two" , "three"]]

two      5
three    6
Name: Colorado, dtype: int64

In [37]:
data.iloc[2]

one       8
two       9
three    10
four     11
Name: Utah, dtype: int64

In [38]:
data.iloc[[2,1]]

          one  two  three  four
Utah        8    9     10    11
Colorado    4    5      6     7

In [39]:
data.iloc[[2,1], [3,1]]

          four  two
Utah        11    9
Colorado     7    5

In [40]:
data.loc[:"Utah" , :"two"]

          one  two
Ohio        0    1
Colorado    4    5
Utah        8    9

In [41]:
data.iloc[:, :3] [ data["three"]>5 ]

          one  two  three
Colorado    4    5      6
Utah        8    9     10
New York   12   13     14

### Indexing options with DataFrame

| Type | Notes |
| :--- | :--- |
| `df[column]` | Select single column or sequence of columns from the DataFrame; special case conveniences: Boolean array (filter rows), slice (slice rows), or Boolean DataFrame (set values based on some criterion) |
| `df.loc[rows]` | Select single row or subset of rows from the DataFrame by label |
| `df.loc[:, cols]` | Select single column or subset of columns by label |
| `df.loc[rows, cols]` | Select both row(s) and column(s) by label |
| `df.iloc[rows]` | Select single row or subset of rows from the DataFrame by integer position |
| `df.iloc[:, cols]` | Select single column or subset of columns by integer position |
| `df.iloc[rows, cols]` | Select both row(s) and column(s) by integer position |
| `df.at[row, col]` | Select a single scalar value by row and column label |
| `df.iat[row, col]` | Select a single scalar value by row and column position (integers) |
| `reindex` method | Select either rows or columns by labels |

## Arithmetic and Data Alignment

In [42]:
s1 = pd.Series([7.3, -2.5, 3.4, 1.5], index=["a", "c", "d", "e"])
s2 = pd.Series([-2.1, 3.6, -1.5, 4, 3.1],index=["a", "c", "e", "f", "g"])

In [43]:
s1

a    7.3
c   -2.5
d    3.4
e    1.5
dtype: float64

In [44]:
s2

a   -2.1
c    3.6
e   -1.5
f    4.0
g    3.1
dtype: float64

In [45]:
s1+s2

a    5.2
c    1.1
d    NaN
e    0.0
f    NaN
g    NaN
dtype: float64

In [46]:
df1 = pd.DataFrame(np.arange(9.).reshape((3, 3)), columns=list("bcd"),
    index=["Ohio", "Texas", "Colorado"])
df2 = pd.DataFrame(np.arange(12.).reshape((4, 3)), columns=list("bde"),
    index=["Utah", "Ohio", "Texas", "Oregon"])

In [47]:
df1

            b    c    d
Ohio      0.0  1.0  2.0
Texas     3.0  4.0  5.0
Colorado  6.0  7.0  8.0

In [48]:
df2

          b     d     e
Utah    0.0   1.0   2.0
Ohio    3.0   4.0   5.0
Texas   6.0   7.0   8.0
Oregon  9.0  10.0  11.0

In [49]:
df1+df2

            b   c     d   e
Colorado  NaN NaN   NaN NaN
Ohio      3.0 NaN   6.0 NaN
Oregon    NaN NaN   NaN NaN
Texas     9.0 NaN  12.0 NaN
Utah      NaN NaN   NaN NaN

### Arithmetic methods with fill values

In [51]:
df1 = pd.DataFrame( np.arange(12).reshape((3,4)) , columns = list("abcd"))
df2 = pd.DataFrame(np.arange(20.).reshape((4, 5)),columns = list("abcde"))

In [52]:
df1

   a  b   c   d
0  0  1   2   3
1  4  5   6   7
2  8  9  10  11

In [53]:
df2

      a     b     c     d     e
0   0.0   1.0   2.0   3.0   4.0
1   5.0   6.0   7.0   8.0   9.0
2  10.0  11.0  12.0  13.0  14.0
3  15.0  16.0  17.0  18.0  19.0

In [54]:
df1+df2

      a     b     c     d   e
0   0.0   2.0   4.0   6.0 NaN
1   9.0  11.0  13.0  15.0 NaN
2  18.0  20.0  22.0  24.0 NaN
3   NaN   NaN   NaN   NaN NaN

In [55]:
df1.add(df2, fill_value = 0 )

      a     b     c     d     e
0   0.0   2.0   4.0   6.0   4.0
1   9.0  11.0  13.0  15.0   9.0
2  18.0  20.0  22.0  24.0  14.0
3  15.0  16.0  17.0  18.0  19.0

In [56]:
df1.rdiv(1)

       a         b         c         d
0    inf  1.000000  0.500000  0.333333
1  0.250  0.200000  0.166667  0.142857
2  0.125  0.111111  0.100000  0.090909

### Flexible arithmetic methods

| Method | Description |
| :--- | :--- |
| `add`, `radd` | Methods for addition (+) |
| `sub`, `rsub` | Methods for subtraction (-) |
| `div`, `rdiv` | Methods for division (/) |
| `floordiv`, `rfloordiv` | Methods for floor division (//) |
| `mul`, `rmul` | Methods for multiplication (*) |
| `pow`, `rpow` | Methods for exponentiation (**) |

### Operations between DataFrame and Series